config/routes.rb
Rails.application.routes.draw do
  resources :contents
  devise_for :users
  root 'pages#home'

  get 'about' => 'pages#about'
  # For details ont he DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
	 belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only:[:edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = current_user.contents.build
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = current_user.contents.build(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:titolo, :descrizione, :price)
    end

    def check_user
      if current_user != @content.user 
        redirect_to root_url, alert:"Scusa ma non hai accesso a questa pagina"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contents/_form.html.erb
<%= form_for(content) do |f| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titolo %>
    <%= f.text_field :titolo %>
  </div>

  <div class="field">
    <%= f.label :descrizione %>
    <%= f.text_area :descrizione %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contents</h1>

<table class="highlight striped responsive-table">
  <thead>
    <tr>
      <th>Titolo</th>
      <th>Descrizione</th>
      <th>Utente</th>
      <th>Email</th>
      <th>Prezzo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <% if content.user == current_user %> 
      <tr>
        <td><%= content.titolo %></td>
        <td><%= content.descrizione %></td>
        <td><%= content.user.name if content.user %></td>
        <td><%= content.user.email if content.user %></td>
        <td><%= content.price %></td>
        <td><%= link_to 'Show', content_path(content) %></td>
        <% if content.user == current_user %>          
          <td><%= link_to 'Edit', edit_content_path(content) %></td>
          <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titolo:</strong>
  <%= @content.titolo %>
</p>

<p>
  <strong>Descrizione:</strong>
  <%= @content.descrizione %>
</p>

<p>
  <strong>Price:</strong>
  <%= @content.price %>
</p>

<% if @content.user == current_user %>
<%= link_to 'Edit', edit_content_path(@content) %>  |
<% end %>
<%= link_to 'Back', contents_path %>

app/views/layouts/_footer.html.erb
<footer class="page-footer #4caf50 green">
  <div class="footer-copyright">
    <div class="container">
      <div class="row">
        <div class="col s4">© 2017 Gianluca</div>
          <div class="col s4">Social</div>
          <div class="col s4">
            <%= link_to "About", about_path, class:"grey-text text-lighten-4 right" %>
          </div>
        </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed">
    <nav class="#4caf50 green">  
        <div class="container nav-wrapper">
          <%= link_to "PrimoSito", root_path, class:"brand-logo" %>
          <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <% if user_signed_in? %>
              <li><%= link_to "LogOut", destroy_user_session_path, method: :delete %></li>
            <%else %>
              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Registrati", new_user_registration_path %></li>
            <% end %>
          </ul>
          <ul class="side-nav" id="mobile-demo">
            <% if user_signed_in? %>
              <li><%= link_to "LogOut", destroy_user_session_path, method: :delete %></li>
            <%else %>
              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Registrati", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  <html>
    <head>
      <title>PrimoSito</title>
      <%= csrf_meta_tags %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>

    <body>

    <%= render "layouts/header" %>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <main class="container">

      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
    </body>
    <script>
       $(".button-collapse").sideNav();
    </script>
  </html>

app/views/pages/about.html.erb
<h1>Chi Siamo</h1>
<p>Siamo un team di sviluppatori che insegna corsi per startup</p>

app/views/pages/home.html.erb
<h1>Questa è la nostra homepage</h1> 